### ISSUE TITLE
Receipt is valid but the returned products array is empty

### ISSUE THREAD

**Issue by izikandrw** [ladeiko/node-apple-receipt-verify#10]
The below code passes a valid receipt and it successfully validates (see verbose logging info I have also attached). However, validate returns an **empty** products array. What am I doing wrong here?

```
async function receiptIsValid(receipt) {
  try {
    const products = await appleReceiptVerify.validate({
      receipt,
    });

    return products[0].expirationDate() < new Date();
  } catch (err) {
    if (err instanceof appleReceiptVerify.EmptyError) {
    } else {
      throw err;
    }
  }
}
```

verbose logging (you can see there is a response from Apple that the receipt is valid and it contains my subscription)
![image](https://user-images.githubusercontent.com/4181895/47942745-b06bbe80-deb8-11e8-8a53-6f0593d09f32.png)

**Comment by ladeiko** [comment]
Try to set 'ignoreExpired' to false (it's true by default)
