### ISSUE TITLE
cancellation_date?

### ISSUE THREAD

**Issue by KjellConnelly** [ladeiko/node-apple-receipt-verify#12]
Hi, and thank you for making this repo :) I was just wondering how I am supposed to check if a subscription has been cancelled. I don't see this info in the product objects, but my app is still in sandbox mode. So I don't really know how to test that either since I don't think I can test Cancelling subscriptions in sandbox mode.

The main thing is that I want to make sure a user should or should not have access to their subscription, whether it is past their `expirationDate`, or they cancelled. Wasn't sure if maybe you edited the `expirationDate` to be the `cancellation_date` if the `cancellation_date` is earlier than the `expirationDate`.

If you haven't done any of this, is there a way you could?

**Comment by ladeiko** [comment]
cancellation_date is filled when user got refund through Apple support
