### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by mangelsnc** [ladeiko/node-apple-receipt-verify#16]
Hi!

First of all, good job! But I miss some information that is not included in the response, I need for example access to the `latest_receipt` and `latest_receipt_info` fields (for example), but you only return the purchased products.

Are you planning in some way to make the response more extended? Or a way to configure it?

**Comment by ladeiko** [comment]
Hi
What info do you need?

**Comment by knuttyse** [comment]
Hi! 
I also appreciate your effort a lot. :)

I see original_transaction_id is available during runtime, but is not declared in the PurchasedProducts interface. Is it safe to assume original_transaction_id?

original_transaction_id seems useful for handling auto renewable subscriptions. 
(My understanding is that original_transaction_id identifies a subscription and could be used if/when server to server notifications don't work)

**Comment by ladeiko** [comment]
original_transaction_id is id of first transaction in purchases chain, it can be used as user identification

**Comment by knuttyse** [comment]
That's right! 👍 

However, I am more comfortable using an original_transaction_id that is already attached to the purchase object.

I think a receipt can contain more than one original_transaction_id if you purchase several things.
For example a user can purchase a non-consumable product and a subscription. Of course, I can filter on productId, but perhaps the user cancelled and then re-subscribed and got a new original_transaction_id?

**Comment by ladeiko** [comment]
every purchase has 'originalTransactionId'

**Comment by knuttyse** [comment]
Cool!
I probably posted this in the wrong place.
I'm using Typescript and didn't realize you are not the maintainer of the type defenitions.
https://www.npmjs.com/package/@types/node-apple-receipt-verify

**Comment by ladeiko** [comment]
You can define interface in your project

**Comment by AlvaroFranco** [comment]
Would be very nice to have some fields like **is_trial_period** which is not currently appearing on the response products. Other fields for managing introductory offers, like **is_in_intro_offer_period**, would be very handy
