### ISSUE TITLE
Compilation fail when installing on macOS

### ISSUE THREAD

**Issue by Olof-IL** [ladeiko/node-apple-receipt-verify#17]
main.c fails to compile when I try to install the module on macOS Catalina 10.15.6, with latest XCode 12.0 (12A7209).

❯ cc --version
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Output from npm:
> node-apple-receipt-verify@1.7.4 preinstall /Users/olle/Documents/git/xxxx/Firebase/functions/node_modules/node-apple-receipt-verify
> mkdir -p bin && cd src && make clean && make || true

rm -f checkreceipt
rm -f ReceiptAttribute.o Payload.o INTEGER.o NativeEnumerated.o NativeInteger.o asn_SET_OF.o constr_SEQUENCE.o constr_SET_OF.o OCTET_STRING.o BIT_STRING.o asn_codecs_prim.o ber_tlv_length.o ber_tlv_tag.o ber_decoder.o der_encoder.o constr_TYPE.o constraints.o xer_support.o xer_decoder.o xer_encoder.o per_support.o per_decoder.o per_encoder.o per_opentype.o main.o
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o ReceiptAttribute.o -c ReceiptAttribute.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o Payload.o -c Payload.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o INTEGER.o -c INTEGER.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o NativeEnumerated.o -c NativeEnumerated.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o NativeInteger.o -c NativeInteger.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o asn_SET_OF.o -c asn_SET_OF.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o constr_SEQUENCE.o -c constr_SEQUENCE.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o constr_SET_OF.o -c constr_SET_OF.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o OCTET_STRING.o -c OCTET_STRING.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o BIT_STRING.o -c BIT_STRING.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o asn_codecs_prim.o -c asn_codecs_prim.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o ber_tlv_length.o -c ber_tlv_length.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o ber_tlv_tag.o -c ber_tlv_tag.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o ber_decoder.o -c ber_decoder.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o der_encoder.o -c der_encoder.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o constr_TYPE.o -c constr_TYPE.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o constraints.o -c constraints.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o xer_support.o -c xer_support.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o xer_decoder.o -c xer_decoder.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o xer_encoder.o -c xer_encoder.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o per_support.o -c per_support.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o per_decoder.o -c per_decoder.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o per_encoder.o -c per_encoder.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o per_opentype.o -c per_opentype.c
cc -I. -I/usr/local/openssl/include -I/usr/local/opt/openssl/include -I/opt/local/include -I/usr/local/include  -o main.o -c main.c
main.c:153:16: error: variable has incomplete type 'EVP_MD_CTX' (aka 'struct evp_md_ctx_st')
    EVP_MD_CTX evp_ctx;
               ^
/usr/local/opt/openssl/include/openssl/ossl_typ.h:92:16: note: forward declaration of 'struct evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
1 error generated.
make: *** [main.o] Error 1
+ node-apple-receipt-verify@1.7.4

I think it's related to this issue, where they made types opaque in OpenSSL 1.1.0:
https://github.com/openssl/openssl/issues/6361

The installed version on my system is OpenSSL 1.1.1g

The module seems to work fine after I deploy it to firebase functions though, but it would be nice if it also worked locally.

**Comment by Olof-IL** [comment]
I guess I should have read already submitted issues more carefully, I see now several others have reported it already, but hopefully my issue contains some new information that can help solve the problem.

**Comment by Olof-IL** [comment]
I created a pull request with a fix for this issue

**Comment by adammlevy** [comment]
I am facing the same issue.  Please advise.

**Comment by ladeiko** [comment]
See v1.8.0
