### ISSUE TITLE
How should I process errors in my nodejs/lambda function?

### ISSUE THREAD

**Issue by Ricardo1980** [ladeiko/node-apple-receipt-verify#21]
Hello,

First of all, thanks for this library. It is working like a charm.
However, there is one thing I don't know how to do.
Lets say I have something like:

```
try {
		const products = await appleReceiptVerify.validate({receipt: receiptContent});
  	} catch (e) {
		if (e instanceof appleReceiptVerify.EmptyError) {
			  console.error('EmptyError');
		} else if (e instanceof appleReceiptVerify.ServiceUnavailableError) {
			console.error('ServiceUnavailableError');
		} else {
			console.error('Unknown error: ' + e);
		}
	}
```

If I use a wrong shared secret on purpose, I see in cloud watch:
`2020-12-23T17:54:08.043Z	384b54b3-a422-466a-bbe8-e87725abe5c3	ERROR	Unknown error: Error: The shared secret you provided does not match the shared secret on file for your account.`

Which makes sense.
But there are about 10 different errors and I would like to process them independently and/or send a code error to the called. I cannot just send a sentence. It would be very difficult to program my logic using sentences instead of error codes.
So, my questions is, how I can know the error code of the error?

Thanks a lot.

**Comment by ladeiko** [comment]
You could try to use e.appleStatus code

**Comment by Ricardo1980** [comment]
You are right!
Thanks a lot.

`2020-12-23T19:17:05.574Z	262ff658-d71b-4dfb-b3bb-0e41b4a1bf1e	ERROR	Unknown error code: 21004`
