### ISSUE TITLE
How do we support the billing grace period?

### ISSUE THREAD

**Issue by Ricardo1980** [ladeiko/node-apple-receipt-verify#23]
How do we support the billing grace period?
I mean, we receive a transaction when the auto renewal subscription is cancelled by apple (a refund), but not when the user cancels the subscription manually.
So, how can I detect that I should provide my service in the billing grace period?

Note: Without using server-to-server notifications. Perhaps that part is mandatory and that is the reason I don't see how to program this.

Thanks for suggestions.

**Comment by ladeiko** [comment]
You can check autorenewal product value, if it presents and on, then just add some additional time yo expiration date while comparison

**Comment by Ricardo1980** [comment]
Thanks a lot for reply.

> You can check autorenewal product value, if it presents and on, then just add some additional time yo expiration date while comparison

Let's say I do that when the user buys a monthly autorenewal subscription.
So, I add 2 weeks to one month, that is, about 6 weeks.

The problem I see is that if the user cancels manually the subscription, the app does not receive any transaction, which means the user will continue using the service for 6 weeks, instead of only one month. 
(He paid for one month, not for 6 weeks)

So, it is very easy to trick the system and get the billing grace period all the time. You just cancel the subscription when you buy it. And after the billing grace period ends, you repeat the process (buy and cancel immediately).

I know how to fix this using server-to-server notifications (I can detect when the user cancels manually. In that case, I just terminate the service)

Any thoughts?
Thanks a lot.

**Comment by ladeiko** [comment]
Every response from node-apple-receipt-verify contains:

   pendingRenewalInfo = [{
            auto_renew_status: ...
            autoRenewStatus: ...,
            product_id: ...,
            productId: ...
          }];


You can check autoRenewStatus if it is true, then you can add your grace period, in another case - not.

**Comment by ladeiko** [comment]
Also try to check other fields of pending_renewal_info like grace_period_expires_date

**Comment by ladeiko** [comment]
Or is_in_billing_retry_period

**Comment by Ricardo1980** [comment]
Yes, but the user does not cancel the subscription at the same time he buys it.

Do you mean that the app logic should check programatically the receipt with my server (and using this library) when the subscription is about to expire to see if the renewal subscription was cancelled by the user? (using pending_renewal_info)
Thanks a lot.

**Comment by ladeiko** [comment]
Just before expiration date verify receipt again and check field

**Comment by Ricardo1980** [comment]
@ladeiko 
Makes sense. Thanks a lot!
