### ISSUE TITLE
Historical Subscription Data

### ISSUE THREAD

**Issue by jrock17** [ladeiko/node-apple-receipt-verify#25]
Thanks for this great package!

I would love to be able to store/update historical subscription renewals in an array. I believe this data is available from Apple via latest_receipt_info, but it's not coming through in this plug-in. 

Can that data be added? Or am I missing something?

> latest_receipt_info contains all the transactions for the subscription, including the initial purchase and subsequent renewals but not including any restores.

https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store

**Comment by ladeiko** [comment]
What do you mean "restores"?

**Comment by jrock17** [comment]
> What do you mean "restores"?

That's from Apple. I'm not concerned about that part really.

But I was hoping to get the array of `all the transactions for the subscription, including the initial purchase and subsequent renewals` that is provided in the latest_receipt_info

**Comment by jrock17** [comment]
Similar to what was asked for here: https://github.com/ladeiko/node-apple-receipt-verify/issues/16

**Comment by jrock17** [comment]
@ladeiko is there a way to get access to the `latest_receipt_info` array of past subscription transactions?

**Comment by ladeiko** [comment]
try to use 'ignoreExpired' option

**Comment by ladeiko** [comment]
> @ladeiko is there a way to get access to the `latest_receipt_info` array of past subscription transactions?

try to use 'ignoreExpired' option
