### ISSUE TITLE
Failed to validate with EmptyError but still want access to original_application_version

### ISSUE THREAD

**Issue by innesngunn** [ladeiko/node-apple-receipt-verify#28]
Hello,

I'm converting a paid app to a free app with in-app purchase. On initial launch, I'd like to validate the `original_application_version` of the app and automatically enable the "paid" features for users who have already paid money for the app. 

Since the `in_app` list is empty (which it should be for my use case), I get an error on validation and (as far I can tell) I don't have access to the `purchasedProducts` result.

Is it possible to ignore the `EmptyError` and gain access to the `purchasedProducts` so that I can access the `original_application_version`?

Thanks!

**Comment by ladeiko** [comment]
Just released 1.10.0 version: added these fields to EmptyError

**Comment by innesngunn** [comment]
Thank you!
