### ISSUE TITLE
validate Error: read ECONNRESET

### ISSUE THREAD

**Issue by victorykong** [ladeiko/node-apple-receipt-verify#29]
What's wrong with this? Apple hasn't given any explanation to status 1. What should I do? At the same time, isRetryable is false. in this case, did the user give money?

`Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  data: undefined,
  appleStatus: 1,
  isRetryable: false
}`

**Comment by ladeiko** [comment]
Just try to retry after some period

**Comment by ladeiko** [comment]
Sometimes it happens just retry
