### ISSUE TITLE
User Subscriptions Cancel doesn't update the reciept 

### ISSUE THREAD

**Issue by AathifMahir** [ladeiko/node-apple-receipt-verify#30]
Hi,

I was using this module with @types/node-apple-receipt-verify module to verify receipt on Firebase, Everything works fine except Subscriptions canceled by users don't update the receipt, you can see the complete code that i was using for Firebase functions in below github repo

https://github.com/flutter/codelabs/tree/master/in_app_purchases/complete/firebase-backend 

This is the link to typescript conversion module that i was using:
https://www.npmjs.com/package/@types/node-apple-receipt-verify

Tested on node-apple-receipt-verify 1.9.3 in IOS Sandbox account

**Comment by ladeiko** [comment]
What do you mean 'CANCEL' - autorenew or refund?

**Comment by AathifMahir** [comment]
@ladeiko Sorry, I mean Subscription Cancelled and Expired one's

**Comment by ladeiko** [comment]
What reaction do you expect from module?

**Comment by AathifMahir** [comment]
sorry, you don't need worry. this issue is from Apple instead of this Module, They don't seem to send the receipt as soon Subscriptions passes it's expired date, it takes around 2 hours minimum to receive the request to server @ladeiko

**Comment by ladeiko** [comment]
ok. so closing issue :)

**Comment by AathifMahir** [comment]
by the way, Does v1.9.3 to 1.10 is there any breaking changes? @ladeiko

**Comment by ladeiko** [comment]
no. just see https://github.com/ladeiko/node-apple-receipt-verify/blob/master/CHANGELOG.md

**Comment by AathifMahir** [comment]
> no. just see https://github.com/ladeiko/node-apple-receipt-verify/blob/master/CHANGELOG.md

Thanks

**Comment by ladeiko** [comment]
you are welcome :)
