### ISSUE TITLE
Validate ERROR: The latest purchase is not sort latest in top

### ISSUE THREAD

**Issue by ly-tai-truong-sai-tec** [ladeiko/node-apple-receipt-verify#31]
Hi team development,

I have using the library to purchase in apple and it always throw error by not matching the latest purchase when using

Library version: 
```
"node-apple-receipt-verify": "^1.8.0",
```
So it is my config apple:
```
appleReceiptVerify.config({
  secret: `***********`,
  environment: ['production'],
  verbose: true,
  excludeOldTransactions: true
})
```
And when I using the validate receiptID
```
const products = await appleReceiptVerify.validate({
      receipt: receiptID
    })
```
When I see the logs the verbose response has been sorted, the latest purchase has on top.
But the response of validate. It is on [length -1] of array 
```
const products = await appleReceiptVerify.validate({
      receipt: receiptID
})
console.log(`purchase apple`, products)

if (Array.isArray(products)) {
      newestProduct = products[0] // it not working correctly
} else {
      newestProduct = products
}
const { productId } = newestProduct
```

So please checking. Maybe it is a issue

**Comment by bupp8999** [comment]
I encounter this problem also. I requested to validate receipt of a product id A, but it returns result of product id B

**Comment by ladeiko** [comment]
You can me sorting using some function. It is not issue of library
