### ISSUE TITLE
EmptyError: failed to validate for empty purchased list

### ISSUE THREAD

**Issue by nrkrishna** [ladeiko/node-apple-receipt-verify#32]
Hello,

Thanks for this great package. Running into an issue where the package fails with the error: "EmptyError: failed to validate for empty purchased list" when verifying a receipt against Apple. I independently verified that the receipt issued in the call is valid by checking the receipt using curl against https://buy.itunes.apple.com/verifyReceipt. 

Any ideas as to why this might be happening?

I'm using version 1.10.0.
Thanks

**Comment by AntoineBouquet** [comment]
Did you found a solution for your problem?

**Comment by nosTa1337** [comment]
@AntoineBouquet did you?

**Comment by kilirushi** [comment]
I am also having problems.

**Comment by melounek** [comment]
Also here... in the code I found mention about this issue: https://developer.apple.com/forums/thread/8954 which causes it and for time being i validate my receipts on `https://buy.itunes.apple.com/verifyReceipt`, but not happy with it.

**Comment by ladeiko** [comment]
This error i special case. You should check for this error after validation
