### ISSUE TITLE
Support HTTP proxy in the validation request

### ISSUE THREAD

**Issue by viktorzavadil** [ladeiko/node-apple-receipt-verify#33]
Hi, validator's collaborator :)

We use proxy for all outgoing requests from our servers. It would be great if node-apple-receipt-verify can use HTTP proxy settings. Environment variable `HTTP_PROXY` is used as standard.

Some hints:
- https://nodejs.org/api/http.html#http_event_connect
- https://stackoverflow.com/a/6781592
- https://stackoverflow.com/a/41027319

It can be easy to fix but on the other hand, can be tricky because of https. It can be easy to fix but on the other hand, can be tricky because of https. If you will use `request` lib for requesting apple, it can be easier.

Thank you for your time.

**Comment by ladeiko** [comment]
Add support for HTTP_PROXY to 1.11.0
