### ISSUE TITLE
Missing isTrialPeriod, isInIntroOfferPeriod when ExpirationDate is not present

### ISSUE THREAD

**Issue by condenast-shraddha** [ladeiko/node-apple-receipt-verify#35]
I have received receipt responses from Apple Sandbox where the expiration_date key was missing/null in the receipt response payload. However, it had isTrialPeriod key populated with false value.

I have observed that this library makes an explicit check ([here](https://github.com/ladeiko/node-apple-receipt-verify/blob/206072402b7df6a0c2389af6dd2a5c342e49556b/lib/apple.js#L400)) on the expiration date before populating any value in the "isTrialPeriod" field. 

Curious what's the reasoning behind this explicit checking on expiration_date. Because, I am seeing Apple sharing valid receipt response with no expiration_date but valid "isTrialPeriod" key value.

Is this an issue?

**Comment by ladeiko** [comment]
fixed in 1.12.1
