### ISSUE TITLE
Does this work for application purchase as well?

### ISSUE THREAD

**Issue by heymartinadams** [ladeiko/node-apple-receipt-verify#4]
Hi @ladeiko, does this also work for application purchase receipt validation, or only for in-app purchase?

**Comment by ladeiko** [comment]
What do you mean saying "application purchase receipt validation"?

**Comment by heymartinadams** [comment]
@ladeiko: not just in-app, but for app purchase. Our app used to only be available via “upfront purchase” (before we changed it to “in-app purchase”)—so you could only download it __once__ you purchased it.

Problem is that when we made that switch to “in-app purchase”, we had no way of validating who had already previously bought the app. So we had to institute a manual transition process.

And today, we occasionally get a few customers who had bought the app years ago, but didn’t upgrade at that time, and think that they have to buy it again via in-app purchase. So I’m looking (again) for a way to validate who previously bought the app via “app purchase” so we can instantly unlock the app for them and they don’t have to contact us manually.

**Comment by ladeiko** [comment]
iOS application receipt contains only information about inapp purchases ONLY.

**Comment by heymartinadams** [comment]
Thank you, @ladeiko 👍
