### ISSUE TITLE
Validate receipts locally and on server both?

### ISSUE THREAD

**Issue by JoxC** [ladeiko/node-apple-receipt-verify#6]
It seems the receipt is validated locally and on app store server twice when device UUID provided ? Is it necessary?

**Comment by ladeiko** [comment]
locally is validated to check UUID and receipt, remote validation is done twice for sandbox/appstore - you can configure to use only appstore environment

**Comment by JoxC** [comment]
Local validation only checks if the receipt is from this device of the specified UUID?

**Comment by ladeiko** [comment]
Yes
