### ISSUE TITLE
Not getting latest data in valid response for some receipts.

### ISSUE THREAD

**Issue by astanb** [ladeiko/node-apple-receipt-verify#9]
For some of the receipts we are verifying there is no data response returned - just an empty array - whilst other receive this data fine. All of these receipts are valid auto-renewing subscriptions and are not returning an error.

I queried the receipts that were not returning data directly with Apple's receipt API and there is indeed a `latest_receipt_info` field which I presume you should be using to pass back as the response.

**Comment by ladeiko** [comment]
Hi. Please describe the problem with details

**Comment by ladeiko** [comment]
Try to set 'ignoreExpired' to false (it's true by default)
